### ISSUE TITLE
Audit server times out responses from multiple servers

### ISSUE THREAD

**Issue by bjschnell** [teamrandint/central#10]
`Error connecting to the audit server for  /errorEvent command:  Get http://172.20.0.3:44455/errorEvent?command=SET_SELL_AMOUNT&errorMessage=Could+not+get+stock+from+database%3A+redigo%3A+nil+returned&funds=720.51&server=transactionserve&stockSymbol=ZWB&transactionNum=118923&username=vo3hMNo7w5: dial tcp 172.20.0.3:44455: connect: connection timed outError connecting to the audit server for  /errorEvent command:  Get http://172.20.0.3:44455/errorEvent?command=CANCEL_SET_SELL&errorMessage=No+existing+sell+trigger+for+this+user+and+stock&server=transactionserve&stockSymbol=DCB&transactionNum=118926&username=rTRN73cQC7: dial tcp 172.20.0.3:44455: connect: connection timed outError: command not implemented 'SET_SELL_TRIGGER,kJaGIaMuNg,NMJ,Error connecting to the audit server for  /errorEvent command:  Get http://172.20.0.3:44455/errorEvent?command=SET_BUY_TRIGGER&errorMessage=No+existing+buy+trigger+for+this+user+and+stock&server=transactionserve&stockSymbol=NCX&transactionNum=137917&username=8Lp0DE5t7W: dial tcp 172.20.0.3:44455: connect: connection timed outError connecting to the audit server for  /errorEvent command:  Get http://172.20.0.3:44455/errorEvent?command=SET_SELL_TRIGGER&errorMessage=No+existing+sell+trigger+for+this+user+and+stock&server=transactionserve&stockSymbol=ZWB&transactionNum=139379&username=cliFiv1eWN: dial tcp 172.20.0.3:44455: connect: connection timed outError: command not implemented 'SET_BUY_TRIGGER,ZE8Rr5fdcn,XHG,`

`Error connecting to the audit server for  /accountTransaction command:  Get http://172.20.0.3:44455/accountTransaction?action=remove&funds=402.59&server=transactionserve&transactionNum=723890&username=KWsQkP8MgA: dial tcp 172.20.0.3:44455: connect: connection timed outError connecting to the audit server for  /errorEvent command:  Get http://172.20.0.3:44455/errorEvent?command=SET_SELL_TRIGGER&errorMessage=No+existing+sell+trigger+for+this+user+and+stock&server=transactionserve&stockSymbol=KQP&transactionNum=724575&username=5InYC86qkp: dial tcp 172.20.0.3:44455: connect: connection timed outError connecting to the audit server for  /errorEvent command:  Get http://172.20.0.3:44455/errorEvent?command=CANCEL_SET_BUY&errorMessage=No+existing+buy+trigger+for+this+user+and+stock&server=transactionserve&stockSymbol=UOH&transactionNum=724480&username=ilfD38GOzH: dial tcp 172.20.0.3:44455: connect: connection timed outError connecting to the audit server for  /errorEvent command:  Get http://172.20.0.3:44455/errorEvent?command=ADD&errorMessage=Failed+to+add+amount+to+the+database+for+user&funds=83276.57&server=transactionserve&transactionNum=724391&username=nY0zlCBZl4: dial tcp 172.20.0.3:44455: connect: connection timed outError: command not implemented 'SET_SELL_TRIGGER,vYFjpiLl4L,JHC,`

or

`Error connecting to the audit server for  /quoteServer command:  Get http://172.20.0.3:44455/quoteServer?cryptokey=Rk%2F4at8fZOb0oMo3gLlqeugzys6WoUUcLj1H1maKB1dsnfPsmMOnBA%3D%3D&price=735.29&quoteServerTime=1521844745195&server=quoteserver&stockSymbol=NBS&transactionNum=80205&username=2tMQYQPe`

**Comment by jarredhawkins** [comment]
I reduced the frequency of these issues by reducing frequency of hitting audit server lol.

Maybe just do that as an easy workaround.  We should look into the spec to see if we need to log every error condition.

**Comment by jarredhawkins** [comment]
Fixed in master. Removed logging of all of the error events by just returning from those functions in the log libraries... In the cases where it still send, just retries until audit server handles it.
