### ISSUE TITLE
Error receiving quote from quoteserver

### ISSUE THREAD

**Issue by bjschnell** [teamrandint/central#11]
While testing 1000 users 
> Error receiving quote from quoteserve.seng:4444

**Comment by ShaeBrown** [comment]
Will print out better details. Also increase timeout, as this could be from a timeout

**Comment by jarredhawkins** [comment]
I put in a retry on my branch when it times out. Seems to resolve this

**Comment by jarredhawkins** [comment]
Fixed and merged into master.
