### ISSUE TITLE
Transaction server - Invalid memory address or nil pointer

### ISSUE THREAD

**Issue by bjschnell** [teamrandint/central#13]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x6200bf]

goroutine 1973504 [running]:
seng468/transaction-server/quote.Query(0xc42801a840, 0xa, 0xc42801a148, 0x3, 0xbf12d, 0x0, 0xc400000000, 0x0, 0x0)
	/go/src/seng468/transaction-server/quote/quoteclient.go:31 +0x4cf
main.TransactionServer.getMaxPurchase(0x6c1e97, 0x10, 0xc4200164f0, 0x10, 0xc4200164f0, 0x10, 0xc420080db0, 0x0, 0x6f5560, 0xc420010b20, ...)
	/go/src/seng468/transaction-server/transaction_server.go:603 +0x66
main.TransactionServer.SetSellAmount(0x6c1e97, 0x10, 0xc4200164f0, 0x10, 0xc4200164f0, 0x10, 0xc420080db0, 0x0, 0x6f5560, 0xc420010b20, ...)
	/go/src/seng468/transaction-server/transaction_server.go:423 +0x165
main.(TransactionServer).SetSellAmount-fm(0xbf12d, 0xc4294563d0, 0x3, 0x3, 0xc4203b8c07, 0x3f9)
	/go/src/seng468/transaction-server/transaction_server.go:61 +0x9e
seng468/transaction-server/socketserver.SocketServer.handleRequest(0xc4200164f0, 0x10, 0xc420080db0, 0x0, 0x6f5fc0, 0xc4281270a8)
	/go/src/seng468/transaction-server/socketserver/socketserver.go:105 +0x1ea
created by seng468/transaction-server/socketserver.SocketServer.Run
	/go/src/seng468/transaction-server/socketserver/socketserver.go:63 +0x28

**Comment by jarredhawkins** [comment]
Possibly fixed this by the quoteserver timeouts... stay tuned

**Comment by jarredhawkins** [comment]
This should be fixed and merged into master. The looping retries ensures a response body can be closed, as a response must be received.
