### ISSUE TITLE
Endpoint average response time in WLG

### ISSUE THREAD

**Issue by jarredhawkins** [teamrandint/central#16]
That way we can provide some statistics and insights as to what calls are talking the longest.

**Comment by jarredhawkins** [comment]
@ShaeBrown the load balancer handles this for total RTT right?

**Comment by ShaeBrown** [comment]
Don't think it does it per endpoint just an average

**Comment by jarredhawkins** [comment]
Ok. I'll look into some WLG changes for this.

**Comment by jarredhawkins** [comment]
#27
